### ISSUE TITLE
List / embeds of all videos

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/teamtrees#6]
With the official YouTube fundraiser I have the ability to tag any videos are part of the fundraiser. I think it would make sense to include all of the Tree coding challenges as well as the live stream. Could we embed all those videos on the landing page? Maybe there is a better design idea. Here is a list:

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bxNsa_3SfCPyF9Md9XvXhR

**Comment by mikakruschel** [comment]
@shiffman maybe the [coding challenge 108 (Barnsley fern)](https://youtu.be/JFugGF1URNo) would also fit in this playlist?

**Comment by shiffman** [comment]
Yes, definitely!
