### ISSUE TITLE
Original returns 404 error

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/teamtrees#8]
<img width="663" alt="Screen Shot 2019-10-28 at 8 52 17 AM" src="https://user-images.githubusercontent.com/191758/67679813-4ddcbf80-f960-11e9-9047-707351778349.png">

**Comment by GypsyDangerous** [comment]
i dont know if this fixes the issue your having but try https://codingtrain.github.io/teamtrees/

**Comment by GypsyDangerous** [comment]
the link you posted on simons issue had uppercase t's in the ``teamtrees`` but it needed to be lowercase

**Comment by GypsyDangerous** [comment]
fixed by #9
